"""LaTeX output: ``values.tex`` macros, the style file, and optional PDF compilation."""

from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

from tracememo.report.tables import latex_escape
from tracememo.store.models import Figure, Table, Value
from tracememo.store.store import ValueStore

TEMPLATES_DIR = Path(__file__).parent / "templates"
STYLE_NAME = "tracememo.sty"


def value_macros(v: Value) -> list[str]:
    """``\\tmdef`` lines defining ``\\val{id}`` and ``\\valu{id}`` for one value."""
    text = v.formatted()
    if isinstance(v.value, str):
        text = latex_escape(text)
    if not v.unit:
        with_unit = text
    elif v.unit == "%":
        with_unit = text + r"\%"
    else:
        with_unit = text + r"\," + latex_escape(v.unit)
    return [f"\\tmdef{{val@{v.id}}}{{{text}}}", f"\\tmdef{{valu@{v.id}}}{{{with_unit}}}"]


def figure_macro(f: Figure, build_dir: Path) -> str:
    """``\\tmdef`` line defining ``\\fig{id}`` as a full figure environment."""
    if f.pdf_path is None:
        raise ValueError(f"figure {f.id} has no PDF file")
    rel = Path(os.path.relpath(f.pdf_path, build_dir)).as_posix()
    base, ext = rel.rsplit(".", 1)
    body = (
        r"\begin{figure}[htbp]\centering"
        f"\\includegraphics[width=\\linewidth]{{{{{base}}}.{ext}}}"
        f"\\caption{{{f.caption}}}\\label{{fig:{f.id}}}"
        r"\end{figure}"
    )
    return f"\\tmdef{{fig@{f.id}}}{{{body}}}"


def table_macro(t: Table, build_dir: Path) -> str:
    """``\\tmdef`` line defining ``\\tab{id}`` as a full table environment."""
    if t.latex_path is None:
        raise ValueError(f"table {t.id} has no LaTeX file")
    rel = Path(os.path.relpath(t.latex_path, build_dir)).as_posix()
    body = (
        r"\begin{table}[htbp]\centering"
        f"\\caption{{{t.caption}}}\\label{{tab:{t.id}}}"
        f"\\input{{{rel}}}"
        r"\end{table}"
    )
    return f"\\tmdef{{tab@{t.id}}}{{{body}}}"


def values_tex(store: ValueStore, build_dir: Path) -> str:
    """The full text of ``values.tex`` for a store."""
    lines = ["% Generated by tracememo from manifest.json. Do not edit.", ""]
    for id_ in sorted(store.values):
        lines += value_macros(store.values[id_])
    for id_ in sorted(store.figures):
        lines.append(figure_macro(store.figures[id_], build_dir))
    for id_ in sorted(store.tables):
        lines.append(table_macro(store.tables[id_], build_dir))
    return "\n".join(lines) + "\n"


def write_latex_support(store: ValueStore, build_dir: Path) -> list[Path]:
    """Write ``values.tex`` and ``tracememo.sty`` into the build directory."""
    build_dir = Path(build_dir)
    build_dir.mkdir(parents=True, exist_ok=True)
    values_path = build_dir / "values.tex"
    values_path.write_text(values_tex(store, build_dir), encoding="utf-8")
    sty_path = build_dir / STYLE_NAME
    shutil.copyfile(TEMPLATES_DIR / STYLE_NAME, sty_path)
    return [values_path, sty_path]


def render_latex(store: ValueStore, template_path: Path, build_dir: Path, out_name: str) -> Path:
    """Copy the LaTeX document into the build dir next to ``values.tex`` and the style file."""
    build_dir = Path(build_dir)
    write_latex_support(store, build_dir)
    out = build_dir / f"{out_name}.tex"
    shutil.copyfile(template_path, out)
    return out


def latexmk_available() -> bool:
    """Whether ``latexmk`` is on PATH."""
    return shutil.which("latexmk") is not None


def compile_pdf(tex_path: Path) -> Path:
    """Compile ``tex_path`` with latexmk in its own directory; return the PDF path."""
    tex_path = Path(tex_path)
    subprocess.run(
        ["latexmk", "-pdf", "-interaction=nonstopmode", "-halt-on-error", tex_path.name],
        cwd=tex_path.parent,
        check=True,
        capture_output=True,
    )
    return tex_path.with_suffix(".pdf")
